### PR TITLE
Use named routing

### PR DESCRIPTION
**Pull request by harikt**
I was actually experimenting with vuejs and tried to remove the hashbang from url so it looks pretty. 

I got an answer from : http://stackoverflow.com/questions/34623833/how-to-remove-hashbang-from-url#34624803

It brings me to here.

And also I wonder whether this is a bug .

With history turned on, you have something like `http://localhost:8080/news/1`  . Then try to refresh the page and all you get is `Cannot GET /news/1`, now when you click back button also it is not working. 

What do you think ?

### CODE REVIEW

**Comment by yyx990803** [comment]
This has nothing to do with using named routes or not - it has to do with how the server is setup. Your server needs to know to serve the same page on `GET /news/1`, if it's just a static file server then you cannot use HTML5 history mode.

**Comment by harikt** [comment]
@yyx990803 thank you.

But don't you think the named routes is useful so users can turn on / off history ?

Regarding the route on server.

What I was thinking was use the server only to return results via api, no rendering and use some frontend tool like vue.js to handle the rendering. But it looks like my idea will not work in that case. I am new to vue.js.

Thank you for your time.

**Comment by LinusBorg** [comment]
> But don't you think the named routes is useful so users can turn on / off history ?

Named routes are not needed for using history mode. What makes you think that?

**Comment by harikt** [comment]
@LinusBorg I was just fixing the other routes. Please try the app and see if that works or not ;-) .

**Pull request closed without merging**
